Products:
  - filename: "9a68938f-4607-4911-afc7-ac03e5fb66f7.jpg"
    dispname: "Jaffels"
    price: "R15.00"
    versions:
      - "Mince"
      - "Curry Mince"
      - "Chicken Mayo"

  - filename: "Burger.jpg"
    dispname: "HamBurger home made beef patties"
    price: "R30,00"
    versions:
      - "PRODUCTS INCLUDE"
      - "Home made beef patties"
      - "Tomato, Fried onions and a slice of cheese"
      - "Variety of sauces"
      - "( BBQ or Tamato and Mustard )"
      - "Ekstra pattie +R10"
      
Not-in-stock:

